### ISSUE TITLE
请问这个是人脸识别的子程序吗？

### ISSUE THREAD

**Issue by XHShane** [yinguobing/image_utility#1]
昨天读了您关于tensorflow关于人脸识别的博文，感觉很有帮助，感谢！最近打算做瞳孔检测方面的工作，由于刚开始进行，所以比较懵圈，有一些简单的问题询问一下，希望能给予帮助。
  但cnn-facial-landmark文件里好像只有landmark.py文件，其他的文件是在这个程序里面吗（但我看到了有关于手的文件，一下子这里面好多文件，不知道用哪一个了）？假如我现在想用muct-master数据集去简单复现一下您的工作，数据集中包含了图片信息和特征点的标签值，那我是不是就只需要切出所需的面部区域，并且将他们对应保存成tfrecord文件就可以直接导入卷积神经网络了呀？（由于现在一直对自己建立的数据集如何导入网络这儿比较困惑，所以问的问题比较低级，但确实在这不太懂呀，万分感谢。）

**Comment by yinguobing** [comment]
> 但cnn-facial-landmark文件里好像只有landmark.py文件，其他的文件是在这个程序里面吗（但我看到了有关于手的文件，一下子这里面好多文件，不知道用哪一个了）？

从post看起，一步一步来，需要用到的文件post里会提到。

> 假如我现在想用muct-master数据集去简单复现一下您的工作，数据集中包含了图片信息和特征点的标签值，那我是不是就只需要切出所需的面部区域，并且将他们对应保存成tfrecord文件就可以直接导入卷积神经网络了呀？

你可以这样尝试，但不见得是最优的做法。可以参考下行业内的论文，找找思路。

**Comment by yinguobing** [comment]
close #1.
Feel free to re-open if not resolved.
